# Generated by Django 3.1.7 on 2021-05-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=160)),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='logo',
        ),
        migrations.AddField(
            model_name='skill',
            name='displayed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='experience',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.ImageField(blank=True, upload_to='static/skill_icons/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
