# Generated by Django 3.1.7 on 2021-05-08 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_auto_20210508_1952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
