# Generated by Django 3.1.7 on 2021-04-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='banner',
            field=models.ImageField(upload_to='static/project_banners/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.ImageField(upload_to='static/project_icons/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ImageField(upload_to='static/skill_icons/'),
        ),
    ]
