# Generated by Django 3.1.7 on 2021-04-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_auto_20210428_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='skill',
            name='experience',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
