# Generated by Django 3.1.7 on 2021-05-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_auto_20210430_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaboration',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='project',
            name='time',
            field=models.CharField(default='', max_length=160),
        ),
    ]
