# Generated by Django 3.1.7 on 2021-05-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_auto_20210508_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.CharField(choices=[('Javascript', 'Javascript'), ('Python', 'Python'), ('Javascript', 'Javascript')], default='', max_length=40),
        ),
    ]
