# Generated by Django 3.1.7 on 2021-05-09 00:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0006_auto_20210508_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Javascript', 'Javascript'), ('Python', 'Python'), ('Javascript', 'Javascript')], default='', max_length=40), default=list, size=None),
        ),
    ]
