# Generated by Django 3.1.7 on 2021-05-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0006_auto_20210430_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.CharField(default='', max_length=160),
        ),
    ]
