# Generated by Django 3.1.7 on 2021-05-13 00:23

from django.db import migrations, models
import django.utils.timezone
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0007_auto_20210508_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='collaboration',
            field=models.CharField(choices=[('Solo', 'Solo'), ('Solo w/ Supervision', 'Solo w/ Supervision'), ('Small Team', 'Small Team'), ('Small Team w/ Supervision', 'Small Team w/ Supervision'), ('Large Team w/ Supervision', 'Large Team w/ Supervision')], default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='project',
            name='role',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(choices=[('Front-End', 'Front-End'), ('Back-End', 'Back-End'), ('Full-Stack', 'Full-Stack'), ('Designer', 'Designer')], default='', max_length=160), default=list, help_text='Front-End, Back-End, Full-Stack, Designer, ', size=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(choices=[('Javascript', 'Javascript'), ('Django', 'Django'), ('CSS', 'CSS'), ('Figma', 'Figma'), ('HTML', 'HTML'), ('Java', 'Java'), ('Redux', 'Redux'), ('MongoDB', 'MongoDB'), ('Nodejs', 'Nodejs'), ('React', 'React'), ('Python', 'Python'), ('SQL', 'SQL')], default='', max_length=40), default=list, help_text='Javascript, Django, CSS, Figma, HTML, Java, Redux, MongoDB, Nodejs, React, Python, SQL, ', size=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='takeaways',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(default=''), default=list, size=None),
        ),
    ]
