# Generated by Django 3.1.7 on 2021-05-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0008_auto_20210430_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='banner',
            field=models.ImageField(blank=True, upload_to='static/project_banners/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
