# Generated by Django 3.1.7 on 2021-05-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0009_auto_20210430_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='orderid',
            field=models.IntegerField(default=0),
        ),
    ]
